on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        job_type: [1, 2]
    steps:
    - uses: actions/checkout@v4
    - uses: sbt/setup-sbt@v1
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
    - if: ${{ matrix.job_type == 1 }}
      run: sbt compile
    - if: ${{ matrix.job_type == 2 }}
      run: |
        mv src/main/scala/A.scala src/main/scala/C.scala
        sbt compile
